### PR TITLE
base gem dependency on logstash-core-plugin-api

### LINKED ISSUE #14: bump logstash-core version requirement
Could we get the logstash-core version requirement bumped and push to rubygems? This plugin won't work if you're using the new logstash-5.0.0-alpha1

```
$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 

$ rpm -q logstash
logstash-5.0.0~alpha1-1.noarch

$ sudo /opt/logstash/bin/logstash-plugin install logstash-input-journald
Validating logstash-input-journald
Installing logstash-input-journald
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.0.0.alpha1)

  In Gemfile:
    logstash-core-plugin-api (= 1.6.0) java depends on
      logstash-core (= 5.0.0.alpha1) java

    logstash-input-journald (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core-plugin-api (= 1.6.0) java depends on
      logstash-core (= 5.0.0.alpha1) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

### PR DESCRIPTION
**Pull request by theadoria**
fixes #14

### CODE REVIEW

**Comment by vaijab** [comment]
@tedwardia have you tested it with logstash 5 alpha?

**Comment by ph** [comment]
The constraints is wrong in this case, they should be set on `logstash-core-plugin-api` and not on the core itself.

remove the dependency on logstash-core and replace it with this one.

```
  s.add_runtime_dependency "logstash-core-plugin-api", "~> 1.0"
```

This will make the plugin compatible for all the v1.0 api.

**Comment by suyograo** [comment]
See https://github.com/logstash-plugins/logstash-filter-csv/blob/master/logstash-filter-csv.gemspec#L23 for example

**Comment by theadoria** [comment]
Just updated the pull request. Does this look okay?

I tested a manual build of this with logstash 5 and it worked without any issues.

**Comment by suyograo** [comment]
LGTM

**Pull request merged**
