### PR TITLE
Update README for git repo and gem version

### PR DESCRIPTION
**Pull request by talset**
- Change the git repository to the new one.
- Replace gem version by logstash-input-journald-*.gem in order to match all gem, even if the gem is updated.

### CODE REVIEW

**Comment by vaijab** [comment]
Could you also include install details from rubygems? The gem has been published to rubygems already.

**Comment by talset** [comment]
@vaijab 
Ok sure. Something like this https://github.com/talset/logstash-input-journald/commit/20cc4bae8e9935547968a3f8ab374bb912994d39 ?

**Comment by vaijab** [comment]
@talset like this: https://github.com/UKHomeOffice/docker-logstash-kubernetes/blob/master/Dockerfile#L12

This is a pretty standard way to install logstash plugins. Logstash pulls them from rubygems automatically.

**Comment by talset** [comment]
Ok changed

**Comment by vaijab** [comment]
LGTM

**Pull request merged**
